---
title: "Figure 1"
output: html_notebook
---

# Dependencies
```{r}
library(tidyverse)
library(tximport)
library(DESeq2)
library(Rtsne)
library(matrixStats)
library(factoextra)
library(ggrepel)
```

# Load the data
```{r}
txi <- readRDS("../../output/txi_mouse.rds")
tpm <- read.csv("../../output/tpm_matrix_mouse.csv", row.names=1)
tpm <- log1p(as.matrix(tpm))
tpm <- tpm[matrixStats::rowVars(tpm) != 0,]
```

```{r}
annotations <- read.csv("../../data/mouse_sample_annotation_cleaned_model_name.csv")
annotations$Sample.code <- gsub("-", ".", annotations$Sample.code)

rownames(annotations) <- annotations$Sample.code

tissue_type <- data.frame(Tissue.type = c("cell line", "IB tumour", "IP tumour"),
                          Tissue.slim = c("Cells", "IB", "IP"))
annotations$Tissue = tissue_type$Tissue.slim[match(annotations$Tissue.type, tissue_type$Tissue.type)]
annotations$Model <- paste0(annotations$Tissue, "_", annotations$Model)

annotation_slim <- annotations %>%
  dplyr::select(c(Sample.code, Model))
```

# Figure 1a - Schematic
Nothing

# Figure 1b - tSNE
We'll calculate that average logTPM for each model to make this cleaner

```{r}
model_avg <- as.data.frame(t(tpm)) %>%
  rownames_to_column(var="Sample.code") %>%
  left_join(annotation_slim, by="Sample.code") %>%
  mutate(Sample.code = NULL) %>%
  pivot_longer(-Model, names_to="Gene", values_to="Expression") %>%
  group_by(Model, Gene) %>%
  dplyr::summarize(AvgExp = mean(Expression)) %>%
  pivot_wider(names_from="Gene", values_from="AvgExp") %>%
  column_to_rownames(var="Model") %>%
  as.matrix() %>% t()
```

We'll run PCA on the top 4k variable genes to get rid of some noise
```{r}
var_genes <- rownames(model_avg)[order(rowSds(model_avg),
                                        decreasing=T)[1:4000]]
```

```{r}
pca_res <- prcomp(t(model_avg[var_genes,]), scale=T, center=T)
rownames(pca_res$x) <- colnames(model_avg)
```

```{r}
fviz_eig(pca_res) + ylab("Percentage variance explained") + 
  theme(axis.text = element_text(size=10, color="black"),
        axis.title = element_text(size=12))
```
We'll run tSNE on 6 PCs

```{r}
ovca_tsne <- Rtsne::Rtsne(pca_res$x[,1:6], perplexity=5) #keep 3*perp < nrow(x)
```

### Plotting
```{r}
plot_dat <- data.frame(Model = colnames(model_avg),
                       tSNE1 = ovca_tsne$Y[,1],
                       tSNE2 = ovca_tsne$Y[,2])
plot_dat$Tissue <- sub("\\_.*", "", plot_dat$Model)
plot_dat$Model <- gsub("Cells_", "", plot_dat$Model)
plot_dat$Model <- gsub("IB_", "", plot_dat$Model)
plot_dat$Model <- gsub("IP_", "", plot_dat$Model)
```

```{r}
cols <- RColorBrewer::brewer.pal(3, "Dark2")

tsne_plot <- ggplot(plot_dat, aes(x=tSNE1, y= tSNE2, label=Model)) + 
  geom_point(shape=21, color="black", aes(fill=Tissue), 
             alpha=0.75, size=3) +
  geom_text_repel(max.overlaps=100, size=2.5,
                  segment.size=0.25,
                  min.segment.length = 0.2) +
  scale_fill_manual(values=cols) +
  #scale_x_continuous(limits=c(-100, 100)) +
  #scale_y_continuous(limits=c(-75, 55)) +
  theme_void() +
  theme(legend.title=element_blank())

ggsave(tsne_plot, filename="./tsne_all_samples.pdf",
       width=4.5, height=4)

tsne_plot
```

# Figure 1c - Replicate consistency
Spearman correlation
```{r}
dat_cor <- cor(tpm[var_genes,], method="spearman")
```

Make tidy
```{r}
dat <- dat_cor %>%
  as.data.frame %>%
  rownames_to_column(var="Sample_1") %>%
  pivot_longer(-Sample_1, names_to="Sample_2", values_to="Correlation")
#dat$Sample_1 <- gsub(".", "-", dat$Sample_1, fixed=T)
#dat$Sample_2 <- gsub(".", "-", dat$Sample_2, fixed=T)
dat$Tissue.type_1 <- annotations$Tissue.type[match(dat$Sample_1, annotations$Sample.code)]
dat$Tissue.type_2 <- annotations$Tissue.type[match(dat$Sample_2, annotations$Sample.code)]
dat$Model_1 <- annotations$Model[match(dat$Sample_1, annotations$Sample.code)]
dat$Model_2 <- annotations$Model[match(dat$Sample_2, annotations$Sample.code)]

dat$Replicate <- ifelse(dat$Model_1 == dat$Model_2 &
                          dat$Tissue.type_1 == dat$Tissue.type_2,
                        "Replicates", "Other")
dat$Replicate <- factor(dat$Replicate, levels=c("Replicates", "Other"))

dat <- filter(dat, Tissue.type_1 == Tissue.type_2)
```

```{r}
old_labels <- c("cell line", "IB tumour", "IP tumour")
new_labels <- c("Cell Lines", "IB Tumours", "IP Tumours")
dat$Tissue.type_1 <- factor(dat$Tissue.type_1, levels=old_labels,
                            labels = new_labels)

cor_plot <- ggplot(dat, aes(x=Replicate, y=Correlation)) +
  geom_boxplot(fill="lightgrey", outlier.size=0.75, outlier.shape = 16,
               width=0.5) +
 # geom_jitter(color="black", alpha=0.5, shape=16, size=0.25) +
  xlab("") + ylab("Spearman correlation\nbetween pairwise samples") +
  facet_wrap(~Tissue.type_1) +
  theme_bw() +
  theme(axis.text.x=element_text(size=12, color="black", angle=45, hjust=1),
        axis.text.y=element_text(size=10, color="black"),
        axis.title = element_text(size=12),
        strip.background = element_blank(),
        strip.text = element_text(size=14))
```

```{r}
ggsave(cor_plot, 
       filename="./spearman_correlation.pdf",
       width=5, height=3)
```

# Figure 1d - Malignant vs. Non-malignant proportion
```{r}
cibersort <- read.csv("../../output/CIBERSORTx_mouseTumours_stose_id8_signature.csv")
```

```{r}
#cibersort$Mixture <- gsub(".", "-", cibersort$Mixture, fixed=T)
cibersort$SampleID <- annotations$SampleID[match(cibersort$Mixture, annotations$Sample.code)]
cibersort$Model <- annotations$Model[match(cibersort$Mixture, annotations$Sample.code)]
cibersort$Tissue.type <- annotations$Tissue.type[match(cibersort$Mixture, annotations$Sample.code)]
```

```{r}
cibersort$Model <- gsub("IB_", "", cibersort$Model, fixed=T)
cibersort$Model <- gsub("IP_", "", cibersort$Model, fixed=T)

ordered_models <- cibersort %>%
  group_by(Model) %>%
  dplyr::summarize(AvgPurity = mean(Malignant)) %>%
  arrange(AvgPurity) %>% 
  pull(Model)

cibersort$Model <- factor(cibersort$Model, levels=ordered_models)
```


```{r}
purity_plot <- ggplot(cibersort, aes(x=Model, y=Malignant)) +
  geom_point(shape=21, size=3, alpha=0.75, color="black", aes(fill=Tissue.type)) +
  scale_fill_manual(values=cols[2:3]) +
  ylab("Estimated purity") + xlab("") + 
  theme_bw() +
  theme(axis.text.x = element_text(size=10, color="black", angle=45, hjust=1),
        axis.text.y = element_text(size=10, color="black"),
        axis.title.y = element_text(size=12),
        legend.title = element_blank(),
        legend.text = element_text(size=12))
```

```{r}
ggsave(purity_plot,
       filename="./tumor_purity.pdf",
       width=5.5, height=3)
```

# Session info 
```{r}
sessionInfo()
```

